---
title: "Project 1"
subtitle: "Data Pre-processing"
author: 
- Utkarsha Negi
- Ruben Pena
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_notebook: default
  pdf_document: default
---


```{r}
install.packages(c("RCurl","VIM","caret"))
```

```{r}
require(RCurl)
abalone<-read.csv(text=getURL("https://raw.githubusercontent.com/rjpena/MA5790/master/Datasets/Abalone/abalone.csv"), header=T)
```


```{r}
names(abalone)[1] <- 'Sex'
summary(abalone)
```

```{r}
library(caret)
#class<-abalone$Rings
#predictors<-abalone[,-9]
dmy<-dummyVars(~., data=abalone,fullRank = T)
transform<- data.frame(predict(dmy, newdata=abalone))
abalone<-transform
```
```{r}
head(abalone)
```

```{r}
summary(abalone)
```



```{r}
library(e1071)
skews <- apply(abalone, 2, skewness)
skews
```

```{r}
YY <- scale(predictors,center=T)
```

```{r}
head(colMeans(YY))
```

```{r}
var(YY)
```

```{r}
a <- aggr(abalone,labels=T)
summary(a)
```


```{r}
require(stats)
library(ggplot2)
```

```{r}
par(mfrow = c(2,4))
for (x in 3:ncol(abalone)) {
  boxplot(abalone[ ,x], horizontal=TRUE, main = paste(names(abalone[x]), "Boxplot"))
}
```

```{r}
par(mfrow = c(2,4)) 
#iterate through columns in num creating histograms of data and naming each as the column name + Histogram
for (x in 3:ncol(abalone)) {
  hist(abalone[ ,x],xlab="", main = paste(names(abalone[x]), "Histogram"))
} 
```



```{r}
ss <- spatialSign(abalone)
```

```{r}
par(mfrow = c(2,4)) 
#iterate through columns in num creating histograms of data and naming each as the column name + Histogram
for (x in 3:9) {
  hist(ss[ ,x],xlab="", main = paste(names(abalone[x]), "Histogram"))
} 

```


```{r}
par(mfrow = c(2,4))
for (x in 3:ncol(ss)) {
  boxplot(ss[ ,x], horizontal=TRUE, main = paste(names(abalone[x])))
}
```


```{r}
require(caret)
pairs(ss)
```
















